- name: 필수 패키지 설치
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: GPG 키 저장
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'

- name: Kubernetes APT 저장소 추가
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
    state: present
    filename: kubernetes

- name: kubelet, kubeadm, kubectl 1.32.0 설치
  apt:
    name:
      - kubelet=1.32.0-1.1
      - kubeadm=1.32.0-1.1
      - kubectl=1.32.0-1.1
    state: present

- name: 패키지 버전 고정 (hold)
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: 현재 swap이 켜져 있는지 확인
  command: swapon --summary
  register: swap_status
  ignore_errors: true
  changed_when: false

- name: swap 비활성화 (켜져 있을 때만)
  command: swapoff -a
  when: swap_status.stdout != ""
  changed_when: true

- name: /etc/fstab 에서 swap 관련 라인 주석처리
  replace:
    path: /etc/fstab
    regexp: '^(/swap.img\s+none\s+swap\s+sw\s+\d\s+\d)'
    replace: '# \1'

- name: kubelet 재시작
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
