- name: /dev/sdb 경로가 존재하는지 확인
  stat:
    path: /dev/sdb
  register: sdb_status

- name: /dev/sdb을 ext4 포맷으로 파일시스템 생성
  filesystem:
    fstype: ext4
    dev: /dev/sdb
  when: sdb_status.stat.exists

- name: 마운트할 디렉토리 생성
  file:
    path: /mnt/data
    state: directory
    mode: '0755'

- name: /dev/sdb 와 /mnt/data 마운트
  mount:
    path: /mnt/data
    src: /dev/sdb
    fstype: ext4
    opts: defaults
    state: mounted

- name: 부팅시 자동마운트 설정
  mount:
    path: /mnt/data
    src: /dev/sdb
    fstype: ext4
    opts: defaults
    state: present
