- name: /dev/sdb 경로가 존재하는지 확인
  stat:
    path: /dev/sdb
  register: sdb_status

- name: /dev/sdb의 파일시스템 유형 확인
  command: lsblk -no FSTYPE /dev/sdb
  register: sdb_fs
  changed_when: false
  check_mode: no
  when: sdb_status.stat.exists

- block:
    - name: /dev/sdb을 ext4로 포맷
      filesystem:
        fstype: ext4
        dev: /dev/sdb

    - name: 마운트할 디렉토리 생성
      file:
        path: /mnt/data
        state: directory
        mode: '0755'

    - name: /dev/sdb 와 /mnt/data 마운트
      mount:
        path: /mnt/data
        src: /dev/sdb
        fstype: ext4
        opts: defaults
        state: mounted

    - name: /etc/fstab에 자동 마운트 설정
      mount:
        path: /mnt/data
        src: /dev/sdb
        fstype: ext4
        opts: defaults
        state: present

  when:
    - sdb_status.stat.exists
    - sdb_fs.stdout != "ext4"
