- name: 시간 동기화 서비스 시작
  systemd:
    name: systemd-timesyncd
    enabled: yes
    state: started

- name: 시간 동기화 강제 수행
  command: timedatectl set-ntp true

- name: 현재 날짜 출력
  command: date
  register: now

- name: 현재 시간 디버깅
  debug:
    var: now.stdout

- name: IP forwarding 설정 확인 및 활성화
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: containerd 설치에 필요한 패키지 설치
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Docker GPG 키 디렉토리 생성
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Docker GPG 키 추가
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: containerd APT 저장소 등록
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    mode: '0644'

- name: APT 캐시 갱신
  apt:
    update_cache: yes
  register: apt_update_result
  until: apt_update_result is succeeded
  retries: 5
  delay: 3

- name: containerd 설치
  apt:
    name: containerd.io
    state: present

- name: containerd 설정파일 덮어쓰기 (SystemdCgroup 설정 전)
  shell: containerd config default | tee /etc/containerd/config.toml
  notify: Restart containerd

- name: containerd 설정 변경 - SystemdCgroup = true로 수정
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  notify: Restart containerd
